# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-30 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitUser',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=250)),
                ('fullname', models.CharField(max_length=250)),
                ('avatar_url', models.CharField(blank=True, default=b'', max_length=1000)),
                ('url', models.CharField(max_length=1000)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
