# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-30 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gituser',
            name='url',
        ),
    ]
