# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-30 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_remove_gituser_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gituser',
            name='fullname',
            field=models.CharField(blank=True, default=b'', max_length=250),
        ),
    ]
