# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-30 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20170930_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gituser',
            name='fullname',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
