# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-30 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest-api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gituser',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
